export const SEARCH_ACTOR = 'SEARCH_ACTOR';
export const SELECT_ACTOR = 'SELECT_ACTOR';
export const COMPARE_CREDITS = 'COMPARE_CREDITS';
export const DELETE_ACTOR = 'DELETE_ACTOR';
export const SEARCH_ERROR = 'SEARCH_ERROR';
